
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace GerasimovAPI.Models
{

using System;
    using System.Collections.Generic;
    
public partial class nameofproduct
{

    public int id { get; set; }

    public string name { get; set; }

    public double price { get; set; }

    public string weight { get; set; }

    public string nameProiz { get; set; }

    public string countryProiz { get; set; }

    public byte[] picture { get; set; }

}

}
